name: nen-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1
  - r-rnbeads=2.10.0
  - r-rnbiodb.hg38
  - r-decomppipeline
  - r-minfi
  - r-methylumi
  - r-conumee
  - r-medecom
  - r-complexheatmap
  - r-pheatmap
  - r-ggplot2
  - r-ggcorrplot
  - python=3.8
  - scikit-learn
  - xgboost
  - pandas
  - numpy
  - notebook
  - jupyterlab
  - pip
  - pip:
      - bigstatsr
